language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: S9LOtsFilxvV4eSRuup7wg7V//heDzaFSM785ta1JZuOL6I2W+7W6YH1ftZsOob0Fpcsv2PQralhaCUHiFtElxzmIAypIVNmGe7s1a6HS/Q7mBrmksbfYXiqhwNJHBmHWctLri9ORxK8dr967MCN6rmNdvrN36rqdWTIdwqULZHWBQvTMFUyJixnK2ETdcfaHBucBOTefj7fAEAvfQDXvDWE5qWmAxarPccpr0y8Yxtd35EzRnVwT0vFzga8PZWuD1iE9sGFxlNCtQpS0IviVT3Tc7QEfg8SLyp+v9esLjlxskjQIEbJL1AIxi7C0FZnT3rm/ygWcOuUce3Om384m6nqGjTXVqUDuz+KqAa5jggU2FxtCzlWUoO06FHDL3Sb5veMiFmw7q5IQXV1133TXM4QLS52dkNnjCwGhIcnXBrXcvNyEBdHV5gnxPw0Gd8Cpvx9jB0MBB4JUndpN3opX8rFJQcClKMCi1IgAF9Eibd+MKrOOPrvfoAJZwM8PAEf+YKnaBuSydPsceNBU8V703KtSp17hdIDs5Bz7C9L4GYeyitPeW1tpdqk5M5r/CJwATFGpjS+4q2FbwEh7Qt81dWYgkYDG2Lk+PCTSpbJ+ND/KmphfEB1/wKEtlDVwPCARLV1lnJttYxlClwUcfwT/HvcHFHUEKSo5XL6Y3b7Npc=
  on:
    tags: true
    repo: nidhaloff/gpx_converter
    python: 3.8
